spring.datasource.url= jdbc:postgresql://dpg-cfot3902i3mo4buvlikg-a.oregon-postgres.render.com:5432/anon_nz6p
spring.datasource.username= anon_nz6p_user
spring.datasource.password= yMtCGXyY4bxCr41I56PXmCiD47iSywY5

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update