spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
spring.datasource.url= jdbc:postgresql://containers-us-west-56.railway.app:6552/railway
spring.datasource.username= postgres
spring.datasource.password= 8Dl39nVKfV4Fbgr4ieyC